version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"
    volumes:
      - /home/thiago/Desktop/Prisma/db:/var/lib/postgresql/data
